### PR TITLE
added symphony Dotenv component package support for non-symphony and …

### LINKED ISSUE #7: mpesa payment b2c
Fatal error: Call to undefined function Safaricom\Mpesa\env() in
env() error.

### PR DESCRIPTION
**Pull request by ngarawakimani**
This is a solution to issue number 7 (Fatal error: Call to undefined function Safaricom\Mpesa\env() in
env() error.)

This error occurs when someone is not using laravel or a symphony based framework 

We need to include symphony Dotenv component as a package and the declare an env() method like laravel does.
Fixes  #7 
@KipchirchirIan
@himanshupatel95

### CODE REVIEW

**Comment by mossey** [comment]
Brilliant work @ngarawakimani.

**Comment by ngarawakimani** [comment]
Thank you @mossey

**Comment by Alecckie** [comment]
Guys, something is not right somewhere. I did all that but still getting the same error
_Call to undefined function Safaricom\Mpesa\env()_
Below is my sample .env file
Capture

Below is my symfony package (2.7...) inside vendor
Capture

Below is a screenshot of my Mpesa.php 
Capture

I dont know where I'm going wrong...kindly help. Seems like the symfony is not loading or something.

**Comment by ngarawakimani** [comment]
You are not supposed  to touch that file, just make your own index.php and then add 
`require '../vendor/autoload.php';`

**Comment by ngarawakimani** [comment]
Am gonna add an example folder later on to show exactly how to use this package especially if you do not use symphony based frameworks.

**Comment by Alecckie** [comment]
I will appreciate ... @ngarawakimani

**Pull request merged**
